#!/bin/bash

set -e

printf "\nhomebrew\n"
## Install homebrew
if command -v brew; then
  echo "Homebrew installed; updating:"
  brew update
else
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  eval $(/opt/homebrew/bin/brew shellenv)
fi

printf "\nbrew packages\n"
# # dependencies
for pkg in git; do
  # if brew list -1 | grep -q "^${pkg}\$"; then
  if [ ! "$(brew ls --versions '$pkg')" ]; then
    echo "Package '$pkg' is installed; updating:"
    brew upgrade "$pkg" && brew cleanup "$pkg" || true
  else
    brew install "$pkg"
  fi
done
