#!/bin/bash

set -e

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

pushd "$(dirname "$SCRIPT_DIR")"

echo "[+] Stowing dotfiles..."
stow . -t $HOME -v --dotfiles \
  --ignore=.DS_Store \
  --ignore=README.md \
  --ignore=aliases.zsh \
  --ignore=key-bindings.zsh \
  --ignore=prompt.zsh  \
  --ignore=installation-docs 

popd 

# Reload shell once installed
echo "[+] Reloading shell..."
exec $SHELL -l


