#!/bin/bash

set -e

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
PARENT_DIR="$(dirname "$SCRIPT_DIR")"

cp ~/Library/Mobile\ Documents/com\~apple\~CloudDocs/Keyboard\ Maestro/Keyboard\ Maestro\ Macros.kmsync $PARENT_DIR/synced
