gui:
  authorColors:
    'jkahne': '#ffff00'
    '*': 'red'
  theme:
    selectedLineBgColor:
      - cyan
git:
  merging:
    args: '--no-ff'
keybinding:
  universal:
    quit: <esc>
    scrollUpMain: <c-k>
    scrollDownMain: <c-j>
    commits:
      moveDownCommit: ''
      moveUpCommit: ''
