#!/bin/bash

set -e

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
DOTFILES_DIR="$(dirname "$SCRIPT_DIR")"

echo "homebrew..."
if ! command -v brew &> /dev/null
then
    echo "Homebrew is not installed. Installing now..."
    # Install Homebrew
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    eval "$(/opt/homebrew/bin/brew shellenv)"
else
    echo "Homebrew is already installed."
fi

echo "git..."
brew install git

if [ ! -d ~/.asdf ]; then
    git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v0.14.0
fi

echo "stow..."
brew install stow

echo "tmux..."
brew install tmux

for pkg in gpg gawk autojump coreutils automake autoconf libyaml readline libxslt libtool openssl@3 fop wxwidgets tree vlc 1password-cli pngpaste lazygit btop broot libpq docker; do
    brew install "$pkg"
done

brew install wget
brew install eza
brew install bat
brew install zsh
brew install zsh-completions
brew install git-delta

echo "iterm2..."
brew reinstall --cask iterm2
brew reinstall --cask keycastr
brew reinstall --cask stats

echo "wezterm..."
brew install --cask wezterm

chmod -R go-w '/opt/homebrew/share'

# this is overridden by stowing
[ -f ~/Library/Application\ Support/lazygit/config.yml ] && rm -f ~/Library/Application\ Support/lazygit/config.yml


[ ! -L $HOME/.dotfiles ] && ln -s "$DOTFILES_DIR" "$HOME/.dotfiles"



# # Not sure if calling this actually works, and I don't want to test out a fresh install right now

./stow.sh

# pushd "$(dirname "$SCRIPT_DIR")"
#
# echo "[+] Stowing dotfiles..."
# stow . -t $HOME -v --dotfiles \
#   --ignore=.DS_Store \
#   --ignore=README.md \
#   --ignore=aliases.zsh \
#   --ignore=font \
#   --ignore=key-bindings.zsh \
#   --ignore=prompt.zsh  \
#   --ignore=scripts \
#   --ignore=synced
#
# popd




printf "\nSwitch to brew zsh\n"
if [ $( cat /etc/shells | grep -E ^$(brew --prefix)/bin/zsh$ ) ]; then
  echo "zsh already set as default shell"
else
 echo $(brew --prefix)/bin/zsh | sudo tee -a /etc/shells
 chsh -s $(brew --prefix)/bin/zsh
fi


brew cleanup

# used by Fork for commandline integrations
pushd "/usr/local"
[ ! -d /usr/local/bin ] && sudo mkdir -p /usr/local/bin
popd


echo "done"
